### ISSUE TITLE
Django crispy forms & custom bootstrap5 theme integration + maintainability

### ISSUE THREAD

**Issue by shawnngtq** [django-crispy-forms/django-crispy-forms#1180]
### Description:

This is a question, not an issue.

Recently, I purchased a bootstrap5 theme from https://themes.getbootstrap.com/. The structure is update the src code and compiled it into html template. Now I want to integrate the compiled html form with django.

My django form is quite complex, multiple formsets with option to add more of each.

I have few options

1. Create the form using django crispy forms layout, 1 field a time, each with theme specific css class
2. Create django crispy forms template pack
3. Directly use the compiled html form, with minimal django crispy forms

I think option 3 seems to be the fastest as you only need to add very small changes, crsf_token etc. I am not sure though how do we use django crispy form to handle specific fields that will generate multiple select options

Which option do you guys think is the best, and why?

**Comment by smithdc1** [comment]
Thanks for your message. 

I've had a think about this and I guess the answer is no one really knows. Certainly I've not looked at those packs to understand what would be required. I think all the options you outline are good ones, I guess it comes down to how much customisation you need and how much you need the funcionatity of crispy-forms that's not templates (layout etc). 

If you can get away with your own templates, then that's a great option. Then depending how much customisation of the exisiting templates you need I'd suggest either having a couple of custom templates as there is a way to [overide](https://django-crispy-forms.readthedocs.io/en/latest/layouts.html#overriding-layout-objects-templates) individual templates. Otherwise you may need to jump in and [create](https://django-crispy-forms.readthedocs.io/en/latest/template_packs.html) a full template pack. 

Hope this helps. Would be interesting to see what approach worked best for you as a guide to others in the future. 

Take care

**Comment by shawnngtq** [comment]
After working with the bootstrap designers to customize my bootstrap5 theme. I come to the conclusion that perhaps option 2 is not very maintainable unless you have a really good understanding how bootstrap CSS/JS.

Personally, I decided to go with hybrid of option 1 and 3, anywhere that requires addition of formset, use crispy form, otherwise, if it's a one-off component, just use html directly.

Crispy has been a great help in reducing the gap between django and frontend, a huge thank you to the contributors.
