### ISSUE TITLE
BooleanField with widget RadioSelect dont render

### ISSUE THREAD

**Issue by GorlikItsMe** [django-crispy-forms/django-crispy-forms#1181]
* Package version: django-crispy-forms==1.11.2
* Django version: 3.1.5
* Python version: 3.7.9
* Template pack: (Optional) crispy-bootstrap5==0.3.1

### Description:
It dont generate correct html code

forms.py
```
class TaskCreateForm(forms.ModelForm):
    send_to_all = forms.BooleanField(
        label="Send all",
        widget=forms.widgets.RadioSelect(
            choices=[
                (True, 'Send all'),
                (False, 'From list'),
            ]
        ),
        initial=False,
    )
```

Should looks something like that
https://getbootstrap.com/docs/5.0/forms/checks-radios/#radios

but now i get only this
```
<div id="div_id_send_to_all" class="mb-3">
    <label for="id_send_to_all_0" class="form-label requiredField">
        Send all<span class="asteriskField">*</span>
    </label>
    <div class=""></div>
</div>
```

**Comment by GorlikItsMe** [comment]
Ok i figureout how to make it works

forms.py
```
send_to_all = forms.ChoiceField(
        label="",
        choices=[
            (True, 'Send all'),
            (False, 'From list'),
        ],
        widget=forms.widgets.RadioSelect(),
        initial=False,
    )
```

**Comment by smithdc1** [comment]
Glad you managed to get your form working 👍

**Comment by interDist** [comment]
I just ran into the same issue (with template pack = bootstrap3). After sifting through the template code, I found the faulty line in layout/radioselect.html (https://github.com/django-crispy-forms/django-crispy-forms/blob/7ce02ff6a4a720fd0969341d4787528dba80a589/crispy_forms/templates/bootstrap3/layout/radioselect.html#L7):

    {% for choice in field.field.choices %}

Instead, this line should be:

    {% for choice in field %}

Which then iterates correctly through the radio choices. There are a few additional changes needed to allow rendering any form field whose widget is `RadioSelect`. I find it strange that this issue was not raised before – in my opinion, it warrants a PR.
