### ISSUE TITLE
Submit a crispy form from javascript code

### ISSUE THREAD

**Issue by RUDIWER** [django-crispy-forms/django-crispy-forms#404]
Hello,

I need to submit a crispy form from javascript ?

Seems not to work ?

   document.getElementById("scherm").click(submit-id-submit);

gives the following error 

 Uncaught ReferenceError: submit is not defined    ???

**Comment by Zopieux** [comment]
This is unrelated to Cripsy Forms. Please learn [Javascript basics](https://google.com/search?q=javascript+submit+form) a bit further.
The actual issue is that `submit-id-submit` is not what you think. It's not a variable name, you are doing two subtractions: `submit - id - submit`. You don't have a `submit` variable, hence the error.
