### ISSUE TITLE
Please support bootstrap4, form-control, is-valid

### ISSUE THREAD

**Issue by JohanHolman** [django-crispy-forms/django-crispy-forms#860]
* Package version: 1.7.2
* Django version: 2.1.2
* Python version: 3.6.5

When a form is send to the server it validates it returns css_class += ' is-invalid' for the validation failures but what a about the support of "is-valid" for the parts that are valid? Is that possible?

**Comment by JohanHolman** [comment]
I want to have the same result as seen on https://getbootstrap.com/docs/4.0/components/forms/#server-side

**Comment by carltongibson** [comment]
@JohanHolman: Happy to add this! 

Problem: we're short a maintainer who's actually using BS4. Would you: 

* A: be prepared to adjust the templates for this?
* B: Look at the other BS4 issues? 

I think they're just a case of adjusting the templates, as I say, and I'd be happy to advise, but, again as I say, not using BS4 myself, it's something we're currently stuck on.

**Comment by smithdc1** [comment]
#871 &  #894 discussed using server side .is-valid and came to the conclusion that it shouldn't. 

Is there a reason for implementing server-side validation rather than client side using the bootstrap javascript, this would allow use of the :valid and :invalid styles and simplify (maybe?) the crispy form logic. [Bootstrap client side validation](https://getbootstrap.com/docs/4.3/components/forms/#custom-styles)

As I see it (and I am very much a novice!!) client side would give a better user experience. With the current approach if something gets marked as .is-invalid then red 'invalid' markings will only go away once the page is re-submitted. e.g. 
![Capture](https://user-images.githubusercontent.com/39445562/64558102-00b67700-d33b-11e9-84bd-e11d46655b6e.PNG)


Looking forward to hearing your thoughts 😃

**Comment by carltongibson** [comment]
Not sure adding client side logic is dependent on crispy is it? (You just add Form Media as with any Django Form...)

We should be able to have this server side if we can determine between: 

* Form was bound but not really submitted. (Django-Filter use-case, say)
* Form was actually submitted. 

A Helper subclass, with an additional attribute, say...? What would this look like...? Is it worth the complication, vs add the additional css attr on validation?

**Comment by smithdc1** [comment]
Thanks for pointing me in the right direction.

**Comment by uri-rodberg** [comment]
> Problem: we're short a maintainer who's actually using BS4. Would you:
> 

Maybe I will be able to help. Contact me by email uri@speedy.net.

**Comment by DmytroLitvinov** [comment]
When we have a game-changer like [htmx](https://github.com/bigskysoftware/htmx) in a web-development which provides ease of using server-side validation - we definitely should revise of integrating in future that feature :)

**Comment by smithdc1** [comment]
This was implemented but quickly reverted due to challenges explained in https://github.com/django-crispy-forms/django-crispy-forms/issues/871

I'll close this, as it was generally agreed to keep `is-invalid` but not `is-valid`. If someone has a solution to those challenges then we can reconsider.
