### ISSUE TITLE
DeprecationWarning: invalid escape sequence \d

### ISSUE THREAD

**Issue by dgrant** [django-crispy-forms/django-crispy-forms#890]
* Package version: 1.7.2
* Django version: 2.2.4
* Python version: 3.7.2

### Description:

Getting the following warning:
```
/env/lib/python3.7/site-packages/crispy_forms/helper.py:371: DeprecationWarning: invalid escape sequence \d
bootstrap_size_match = re.findall('col-(lg|md|sm|xs)-(\d+)', self.label_class)
```

I'm not doing anything fancy with crispy, this is very minimal and normal usage.

**Comment by carltongibson** [comment]
Thanks for the report yes, this was fixed in https://github.com/django-crispy-forms/django-crispy-forms/commit/0394c9c49ae0519e92c83d7a37c204f6999076a9, which is in `master` now, and they'll be a new release in the Autumn, before Django 3.0 (in December). 

(Issue is those regex strings should use `r` so the `\d` doesn't look like an escape sequence...)
