### ISSUE TITLE
Bootstrap 4 file field rendering incorrectly due to incorrect class

### ISSUE THREAD

**Issue by CormacMOB** [django-crispy-forms/django-crispy-forms#962]
* Package version: 1.8.1
* Django version: 2.2.9
* Python version: 3.6.9
* Template pack: Bootstrap 4

### Description:

A file field is rendering as
<input type="file" name="media_file" class="adminfilewidget form-control" id="id_media_file">

With the "form-control" class

The correct class string would be "form-control-file"
https://getbootstrap.com/docs/4.0/components/forms/

Adding that class in FormHelper.layout using the css_class attribute does not seem to fix the issue as the resulting class string is:

"form-control-file adminfilewidget form-control"

It seems to me that the line 142 of templatetags/crispy_forms_fields.py is incorrectly appending the "form-control" class to file fields. 

But I may be missing something. 
 
Generated HTML:
<input type="file" name="media_file" class="adminfilewidget form-control" id="id_media_file">

Expected HTML:
<input type="file" name="media_file" class="adminfilewidget form-control-file" id="id_media_file">

**Comment by jonesim** [comment]
In what way is it rendered incorrectly?

**Comment by smithdc1** [comment]
[Here](https://crispy-forms-project.herokuapp.com/bootstrap4) is the test project with version 1.8.1. The default layout has `use_custom_control = True`, and Horizontal has `use_custom_control = False`.

Horizontal forms have a line border due to `form-control`, a change to `form-control-file` removes the line. 

The default forms (new style) have the `class="fileinput fileUpload form-control custom-file-input"` so removing the form control looks to be right for this as well.

Must admit I'm a little puzzled as image in [docs](https://django-crispy-forms.readthedocs.io/en/latest/form_helper.html#bootstrap-4-helper-attributes) and comments at the time seemed to support. 🤷‍♂ 

@CormacMOB you have the part of the code which needs changing - are you able to look at raising a PR?

**Comment by CormacMOB** [comment]
Apologies for the delay in getting back.

@jonesim My issue is the border rendering described by smithdc1.  Although its also affected by some other styling too.

@smithdc1 I will take a look this evening.

**Comment by smithdc1** [comment]
closed by #964
